version: 1.2
workflows:
 - name: C-BIRD
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_c-bird.wdl
   testParameterFiles:
    - /misc/empty.json

 - name: cbird-insert_size_dist
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_insert_size.wdl
   testParameterFiles:
    - /misc/empty.json
