version: 1.2
workflows:
 - name: cbird-workflow
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_c-bird.wdl
   testParameterFiles:
    - empty.json

 - name: cbird-insert_size_dist
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_insert_size.wdl
   testParameterFiles:
    - empty.json
