version: 1.2
workflows:
 - name: cbird-workflow
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_c-bird.wdl
   testParameterFiles:
    - empty.json
 - name: spades-test
  subclass: WDL
  primaryDescriptorPath: /workflows/spades_wf.wdl
  testParameterFiles:
    - empty.json